# Generated by Django 5.2.4 on 2025-08-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='in_transit',
            field=models.BooleanField(default=False),
        ),
    ]
