# Generated by Django 5.2.4 on 2025-08-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_rider_in_transit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rider',
            name='in_transit',
        ),
    ]
