# Generated by Django 5.2.4 on 2025-07-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_active_user_is_admin_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
