# Generated by Django 5.2.4 on 2025-07-29 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('restaurant_image', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('inside_image1', models.ImageField(blank=True, null=True, upload_to='restaurant_inside_images/')),
                ('inside_image2', models.ImageField(blank=True, null=True, upload_to='restaurant_inside_images/')),
                ('inside_image3', models.ImageField(blank=True, null=True, upload_to='restaurant_inside_images/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('chef_name', models.CharField(blank=True, max_length=255, null=True)),
                ('chef_image', models.ImageField(blank=True, null=True, upload_to='chef_images/')),
                ('rating', models.FloatField(default=0.0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
