# Generated by Django 5.2.4 on 2025-07-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Indian', 'Indian'), ('Bengali', 'Bengali'), ('Fast Food', 'Fast Food')], default='Bengali', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='offers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
