# Generated by Django 5.2.4 on 2025-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_category_restaurant_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='estimated_delivery_time',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
    ]
