# Generated by Django 5.2.4 on 2025-08-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_restaurant_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
