# Generated by Django 5.2.4 on 2025-07-31 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_cart_ordered_alter_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Preparing', 'Preparing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20, null=True),
        ),
    ]
