# Generated by Django 5.2.4 on 2025-08-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Preparing', 'Preparing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Completed without Rider', 'Completed without Rider'), ('Rider Assigned', 'Rider Assigned'), ('On the way', 'On the way')], max_length=50, null=True),
        ),
    ]
